### ISSUE TITLE
Email adresses put in bold are broken in the rendering

### ISSUE THREAD

**Issue by stof** [symfony-tools/docs-builder#134] opened 2021-11-29 13:13 UTC
Detected on https://symfony.com/doc/current/contributing/code_of_conduct/care_team.html which has the following content in the source:

```
Here are all the members of the CARE team (in alphabetic order). You can contact
any of them directly using the contact details below or you can also contact all
of them at once by emailing **care@symfony.com**:
```

The docs builder currently render this like that:

```html
<p>Here are all the members of the CARE team (in alphabetic order). You can contact
any of them directly using the contact details below or you can also contact all
of them at once by emailing <a href="mailto:**care@symfony.com" class="reference internal">**care@symfony.com</a>**:</p>
```

the `**` before the email is taken as part of the email reference, which breaks the `mailto` link (the link goes to the wrong email) and is probably also what breaks the bold rendering.

**Comment by javiereguiluz** [comment] 2021-11-29 14:14
I think it's a duplicate of #128, which adds a failing test for this (but sadly not a solution).

**Comment by stof** [comment] 2021-11-29 14:16
indeed. I looked at issues but not at PRs.

**Closed** 2021-11-29 14:56 UTC
